spring:
  application:
    name: fluxpay
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: user_dev
    password: password_dev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect